# Generated by Django 5.1.5 on 2025-02-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_counter_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_product",
            field=models.CharField(
                max_length=150, verbose_name="Наименование продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=20, verbose_name="Цена"),
        ),
    ]
