# Generated by Django 5.1.5 on 2025-02-26 11:32

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0003_alter_product_description_alter_product_name_product_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение",
                null=True,
                upload_to="media/catalog/image",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                    catalog.models.validate_image_size,
                ],
                verbose_name="Изображение",
            ),
        ),
    ]
